name: Release

on:
  push:
    tags:
      - "*"

jobs:
  server:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: |
          yarn --frozen-lockfile
          yarn global add turbo@1.5.5

      # - name: Test
      #   run: turbo run test --scope=api

      - name: Docker login
        run: docker login -u bitmetro -p ${{ secrets.DOCKER_PASSWORD }} docker.io

      - name: Build and push server
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: Dockerfile
          tags: bitmetro/callisto-server:${{ github.ref_name }}
          build-args: |
            SCOPE=api
            PORT=7000
          
  client:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: |
          yarn --frozen-lockfile
          yarn global add turbo@1.5.5

      # - name: Test
        # run: turbo run test --scope=dashboard

      - name: Docker login
        run: docker login -u bitmetro -p ${{ secrets.DOCKER_PASSWORD }} docker.io

      - name: Build and push client
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: Dockerfile
          tags: bitmetro/callisto-client:${{ github.ref_name }}
          build-args: |
            SCOPE=dashboard
            PORT=7001
